// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP_YAJPp_sBU2qKFAoZwoQmpWVpa8tEeY',
    appId: '1:132751643643:web:19988c3d8676db25b7f15e',
    messagingSenderId: '132751643643',
    projectId: 'coursework-c5884',
    authDomain: 'coursework-c5884.firebaseapp.com',
    storageBucket: 'coursework-c5884.appspot.com',
    measurementId: 'G-SYJ2MH38S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVGcOUrIEERO3jP2cyJ43-JZcBsQZassY',
    appId: '1:132751643643:android:b3e73211e82c0497b7f15e',
    messagingSenderId: '132751643643',
    projectId: 'coursework-c5884',
    storageBucket: 'coursework-c5884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcDyaK2i0mGCUUbqIiRfIebpuO-LQugYs',
    appId: '1:132751643643:ios:9e74d3df90902e8bb7f15e',
    messagingSenderId: '132751643643',
    projectId: 'coursework-c5884',
    storageBucket: 'coursework-c5884.appspot.com',
    iosBundleId: 'com.example.setupApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcDyaK2i0mGCUUbqIiRfIebpuO-LQugYs',
    appId: '1:132751643643:ios:6638ca9ed85c71edb7f15e',
    messagingSenderId: '132751643643',
    projectId: 'coursework-c5884',
    storageBucket: 'coursework-c5884.appspot.com',
    iosBundleId: 'com.example.setupApplication.RunnerTests',
  );
}
